/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RatgeberRouteImport } from './routes/ratgeber'
import { Route as NachrichtenRouteImport } from './routes/nachrichten'
import { Route as EBikesRouteImport } from './routes/e-bikes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtikelSlugRouteImport } from './routes/artikel.$slug'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RatgeberRoute = RatgeberRouteImport.update({
  id: '/ratgeber',
  path: '/ratgeber',
  getParentRoute: () => rootRouteImport,
} as any)
const NachrichtenRoute = NachrichtenRouteImport.update({
  id: '/nachrichten',
  path: '/nachrichten',
  getParentRoute: () => rootRouteImport,
} as any)
const EBikesRoute = EBikesRouteImport.update({
  id: '/e-bikes',
  path: '/e-bikes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelSlugRoute = ArtikelSlugRouteImport.update({
  id: '/artikel/$slug',
  path: '/artikel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/e-bikes': typeof EBikesRoute
  '/nachrichten': typeof NachrichtenRoute
  '/ratgeber': typeof RatgeberRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tests': typeof TestsRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e-bikes': typeof EBikesRoute
  '/nachrichten': typeof NachrichtenRoute
  '/ratgeber': typeof RatgeberRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tests': typeof TestsRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/e-bikes': typeof EBikesRoute
  '/nachrichten': typeof NachrichtenRoute
  '/ratgeber': typeof RatgeberRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tests': typeof TestsRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/e-bikes'
    | '/nachrichten'
    | '/ratgeber'
    | '/sitemap.xml'
    | '/tests'
    | '/artikel/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/e-bikes'
    | '/nachrichten'
    | '/ratgeber'
    | '/sitemap.xml'
    | '/tests'
    | '/artikel/$slug'
  id:
    | '__root__'
    | '/'
    | '/e-bikes'
    | '/nachrichten'
    | '/ratgeber'
    | '/sitemap.xml'
    | '/tests'
    | '/artikel/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EBikesRoute: typeof EBikesRoute
  NachrichtenRoute: typeof NachrichtenRoute
  RatgeberRoute: typeof RatgeberRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestsRoute: typeof TestsRoute
  ArtikelSlugRoute: typeof ArtikelSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber': {
      id: '/ratgeber'
      path: '/ratgeber'
      fullPath: '/ratgeber'
      preLoaderRoute: typeof RatgeberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nachrichten': {
      id: '/nachrichten'
      path: '/nachrichten'
      fullPath: '/nachrichten'
      preLoaderRoute: typeof NachrichtenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e-bikes': {
      id: '/e-bikes'
      path: '/e-bikes'
      fullPath: '/e-bikes'
      preLoaderRoute: typeof EBikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/$slug': {
      id: '/artikel/$slug'
      path: '/artikel/$slug'
      fullPath: '/artikel/$slug'
      preLoaderRoute: typeof ArtikelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EBikesRoute: EBikesRoute,
  NachrichtenRoute: NachrichtenRoute,
  RatgeberRoute: RatgeberRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestsRoute: TestsRoute,
  ArtikelSlugRoute: ArtikelSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
