/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RatgeberRouteImport } from './routes/ratgeber'
import { Route as NachrichtenRouteImport } from './routes/nachrichten'
import { Route as MnvRouteImport } from './routes/mnv'
import { Route as EBikesRouteImport } from './routes/e-bikes'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtikelSlugRouteImport } from './routes/artikel.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminArticlesRouteImport } from './routes/_authenticated/admin.articles'
import { Route as AuthenticatedAdminArticlesNewRouteImport } from './routes/_authenticated/admin.articles_.new'
import { Route as AuthenticatedAdminArticlesIdRouteImport } from './routes/_authenticated/admin.articles_.$id'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RatgeberRoute = RatgeberRouteImport.update({
  id: '/ratgeber',
  path: '/ratgeber',
  getParentRoute: () => rootRouteImport,
} as any)
const NachrichtenRoute = NachrichtenRouteImport.update({
  id: '/nachrichten',
  path: '/nachrichten',
  getParentRoute: () => rootRouteImport,
} as any)
const MnvRoute = MnvRouteImport.update({
  id: '/mnv',
  path: '/mnv',
  getParentRoute: () => rootRouteImport,
} as any)
const EBikesRoute = EBikesRouteImport.update({
  id: '/e-bikes',
  path: '/e-bikes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelSlugRoute = ArtikelSlugRouteImport.update({
  id: '/artikel/$slug',
  path: '/artikel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminArticlesRoute =
  AuthenticatedAdminArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminArticlesNewRoute =
  AuthenticatedAdminArticlesNewRouteImport.update({
    id: '/articles_/new',
    path: '/articles/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminArticlesIdRoute =
  AuthenticatedAdminArticlesIdRouteImport.update({
    id: '/articles_/$id',
    path: '/articles/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/e-bikes': typeof EBikesRoute
  '/mnv': typeof MnvRoute
  '/nachrichten': typeof NachrichtenRoute
  '/ratgeber': typeof RatgeberRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tests': typeof TestsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/admin/articles/new': typeof AuthenticatedAdminArticlesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e-bikes': typeof EBikesRoute
  '/mnv': typeof MnvRoute
  '/nachrichten': typeof NachrichtenRoute
  '/ratgeber': typeof RatgeberRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tests': typeof TestsRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/admin/articles/new': typeof AuthenticatedAdminArticlesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/e-bikes': typeof EBikesRoute
  '/mnv': typeof MnvRoute
  '/nachrichten': typeof NachrichtenRoute
  '/ratgeber': typeof RatgeberRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tests': typeof TestsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/_authenticated/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/articles_/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/_authenticated/admin/articles_/new': typeof AuthenticatedAdminArticlesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/e-bikes'
    | '/mnv'
    | '/nachrichten'
    | '/ratgeber'
    | '/sitemap.xml'
    | '/tests'
    | '/admin'
    | '/artikel/$slug'
    | '/admin/articles'
    | '/admin/media'
    | '/admin/users'
    | '/admin/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/e-bikes'
    | '/mnv'
    | '/nachrichten'
    | '/ratgeber'
    | '/sitemap.xml'
    | '/tests'
    | '/artikel/$slug'
    | '/admin/articles'
    | '/admin/media'
    | '/admin/users'
    | '/admin'
    | '/admin/articles/$id'
    | '/admin/articles/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/e-bikes'
    | '/mnv'
    | '/nachrichten'
    | '/ratgeber'
    | '/sitemap.xml'
    | '/tests'
    | '/_authenticated/admin'
    | '/artikel/$slug'
    | '/_authenticated/admin/articles'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/articles_/$id'
    | '/_authenticated/admin/articles_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EBikesRoute: typeof EBikesRoute
  MnvRoute: typeof MnvRoute
  NachrichtenRoute: typeof NachrichtenRoute
  RatgeberRoute: typeof RatgeberRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestsRoute: typeof TestsRoute
  ArtikelSlugRoute: typeof ArtikelSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber': {
      id: '/ratgeber'
      path: '/ratgeber'
      fullPath: '/ratgeber'
      preLoaderRoute: typeof RatgeberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nachrichten': {
      id: '/nachrichten'
      path: '/nachrichten'
      fullPath: '/nachrichten'
      preLoaderRoute: typeof NachrichtenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mnv': {
      id: '/mnv'
      path: '/mnv'
      fullPath: '/mnv'
      preLoaderRoute: typeof MnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e-bikes': {
      id: '/e-bikes'
      path: '/e-bikes'
      fullPath: '/e-bikes'
      preLoaderRoute: typeof EBikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/$slug': {
      id: '/artikel/$slug'
      path: '/artikel/$slug'
      fullPath: '/artikel/$slug'
      preLoaderRoute: typeof ArtikelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/articles': {
      id: '/_authenticated/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AuthenticatedAdminArticlesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/articles_/new': {
      id: '/_authenticated/admin/articles_/new'
      path: '/articles/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AuthenticatedAdminArticlesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/articles_/$id': {
      id: '/_authenticated/admin/articles_/$id'
      path: '/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AuthenticatedAdminArticlesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminArticlesRoute: typeof AuthenticatedAdminArticlesRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminArticlesIdRoute: typeof AuthenticatedAdminArticlesIdRoute
  AuthenticatedAdminArticlesNewRoute: typeof AuthenticatedAdminArticlesNewRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminArticlesRoute: AuthenticatedAdminArticlesRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminArticlesIdRoute: AuthenticatedAdminArticlesIdRoute,
  AuthenticatedAdminArticlesNewRoute: AuthenticatedAdminArticlesNewRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EBikesRoute: EBikesRoute,
  MnvRoute: MnvRoute,
  NachrichtenRoute: NachrichtenRoute,
  RatgeberRoute: RatgeberRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestsRoute: TestsRoute,
  ArtikelSlugRoute: ArtikelSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
