/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VergleichRouteImport } from './routes/vergleich'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SicherheitRouteImport } from './routes/sicherheit'
import { Route as RedaktionRouteImport } from './routes/redaktion'
import { Route as RatgeberRouteImport } from './routes/ratgeber'
import { Route as PasstZuDirRouteImport } from './routes/passt-zu-dir'
import { Route as NutzungsbedingungenRouteImport } from './routes/nutzungsbedingungen'
import { Route as NewsSitemapDotxmlRouteImport } from './routes/news-sitemap[.]xml'
import { Route as NachrichtenRouteImport } from './routes/nachrichten'
import { Route as MerklisteRouteImport } from './routes/merkliste'
import { Route as MeinRadRouteImport } from './routes/mein-rad'
import { Route as MediadatenRouteImport } from './routes/mediadaten'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KarteRouteImport } from './routes/karte'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as FavoritenRouteImport } from './routes/favoriten'
import { Route as FahrraederRouteImport } from './routes/fahrraeder'
import { Route as EBikesRouteImport } from './routes/e-bikes'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as BildnachweiseRouteImport } from './routes/bildnachweise'
import { Route as BarrierefreiheitRouteImport } from './routes/barrierefreiheit'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsWerkzeugListeRouteImport } from './routes/tools.werkzeug-liste'
import { Route as ToolsWartungsintervalleRouteImport } from './routes/tools.wartungsintervalle'
import { Route as ToolsVersicherungRouteImport } from './routes/tools.versicherung'
import { Route as ToolsVergleichRouteImport } from './routes/tools.vergleich'
import { Route as ToolsUebersetzungRechnerRouteImport } from './routes/tools.uebersetzung-rechner'
import { Route as ToolsUebersetzungRouteImport } from './routes/tools.uebersetzung'
import { Route as ToolsTourenplanerRouteImport } from './routes/tools.tourenplaner'
import { Route as ToolsStvoRouteImport } from './routes/tools.stvo'
import { Route as ToolsSonnenzeitenRouteImport } from './routes/tools.sonnenzeiten'
import { Route as ToolsSicherheitsCheckRouteImport } from './routes/tools.sicherheits-check'
import { Route as ToolsReifendruckRechnerRouteImport } from './routes/tools.reifendruck-rechner'
import { Route as ToolsReifendruckRouteImport } from './routes/tools.reifendruck'
import { Route as ToolsRahmengroessenRechnerRouteImport } from './routes/tools.rahmengroessen-rechner'
import { Route as ToolsRahmengroesseRouteImport } from './routes/tools.rahmengroesse'
import { Route as ToolsRadelScoreGuideRouteImport } from './routes/tools.radel-score-guide'
import { Route as ToolsRadelScoreRouteImport } from './routes/tools.radel-score'
import { Route as ToolsPannenhilfeRouteImport } from './routes/tools.pannenhilfe'
import { Route as ToolsLuftqualitaetRouteImport } from './routes/tools.luftqualitaet'
import { Route as ToolsKaufberaterAiRouteImport } from './routes/tools.kaufberater-ai'
import { Route as ToolsKaufberaterRouteImport } from './routes/tools.kaufberater'
import { Route as ToolsKalorienRechnerRouteImport } from './routes/tools.kalorien-rechner'
import { Route as ToolsKalorienRouteImport } from './routes/tools.kalorien'
import { Route as ToolsJobradLeasingRechnerRouteImport } from './routes/tools.jobrad-leasing-rechner'
import { Route as ToolsJobradLeasingRouteImport } from './routes/tools.jobrad-leasing'
import { Route as ToolsFoerderungRouteImport } from './routes/tools.foerderung'
import { Route as ToolsFahrradWetterRouteImport } from './routes/tools.fahrrad-wetter'
import { Route as ToolsFahrradVergleichRouteImport } from './routes/tools.fahrrad-vergleich'
import { Route as ToolsEcoRouteRouteImport } from './routes/tools.eco-route'
import { Route as ToolsEbikeReichweiteRechnerRouteImport } from './routes/tools.ebike-reichweite-rechner'
import { Route as ToolsEbikeReichweiteRouteImport } from './routes/tools.ebike-reichweite'
import { Route as ToolsEbikeFoerderungRechnerRouteImport } from './routes/tools.ebike-foerderung-rechner'
import { Route as ToolsDiebstahlschutzRouteImport } from './routes/tools.diebstahlschutz'
import { Route as ToolsBussgeldRouteImport } from './routes/tools.bussgeld'
import { Route as NewsletterBestaetigenRouteImport } from './routes/newsletter.bestaetigen'
import { Route as NewsletterAbmeldenRouteImport } from './routes/newsletter.abmelden'
import { Route as FahrraederSlugRouteImport } from './routes/fahrraeder.$slug'
import { Route as ArtikelSlugRouteImport } from './routes/artikel.$slug'
import { Route as AuthenticatedMnvRouteImport } from './routes/_authenticated/mnv'
import { Route as AuthenticatedMnvIndexRouteImport } from './routes/_authenticated/mnv.index'
import { Route as AuthenticatedMnvUsersRouteImport } from './routes/_authenticated/mnv.users'
import { Route as AuthenticatedMnvNewsletterRouteImport } from './routes/_authenticated/mnv.newsletter'
import { Route as AuthenticatedMnvMessagesRouteImport } from './routes/_authenticated/mnv.messages'
import { Route as AuthenticatedMnvMediaRouteImport } from './routes/_authenticated/mnv.media'
import { Route as AuthenticatedMnvBikesRouteImport } from './routes/_authenticated/mnv.bikes'
import { Route as AuthenticatedMnvAutoArticlesRouteImport } from './routes/_authenticated/mnv.auto-articles'
import { Route as AuthenticatedMnvArticlesRouteImport } from './routes/_authenticated/mnv.articles'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicNewsletterUnsubscribeRouteImport } from './routes/api.public.newsletter.unsubscribe'
import { Route as ApiPublicNewsletterDispatchRouteImport } from './routes/api.public.newsletter.dispatch'
import { Route as ApiPublicArticlesAutoGenerateRouteImport } from './routes/api.public.articles.auto-generate'
import { Route as ApiPublicArticleImagePathRouteImport } from './routes/api.public.article-image.$path'
import { Route as AuthenticatedMnvBikesNewRouteImport } from './routes/_authenticated/mnv.bikes_.new'
import { Route as AuthenticatedMnvBikesIdRouteImport } from './routes/_authenticated/mnv.bikes_.$id'
import { Route as AuthenticatedMnvArticlesNewRouteImport } from './routes/_authenticated/mnv.articles_.new'
import { Route as AuthenticatedMnvArticlesIdRouteImport } from './routes/_authenticated/mnv.articles_.$id'

const VergleichRoute = VergleichRouteImport.update({
  id: '/vergleich',
  path: '/vergleich',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SicherheitRoute = SicherheitRouteImport.update({
  id: '/sicherheit',
  path: '/sicherheit',
  getParentRoute: () => rootRouteImport,
} as any)
const RedaktionRoute = RedaktionRouteImport.update({
  id: '/redaktion',
  path: '/redaktion',
  getParentRoute: () => rootRouteImport,
} as any)
const RatgeberRoute = RatgeberRouteImport.update({
  id: '/ratgeber',
  path: '/ratgeber',
  getParentRoute: () => rootRouteImport,
} as any)
const PasstZuDirRoute = PasstZuDirRouteImport.update({
  id: '/passt-zu-dir',
  path: '/passt-zu-dir',
  getParentRoute: () => rootRouteImport,
} as any)
const NutzungsbedingungenRoute = NutzungsbedingungenRouteImport.update({
  id: '/nutzungsbedingungen',
  path: '/nutzungsbedingungen',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSitemapDotxmlRoute = NewsSitemapDotxmlRouteImport.update({
  id: '/news-sitemap.xml',
  path: '/news-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NachrichtenRoute = NachrichtenRouteImport.update({
  id: '/nachrichten',
  path: '/nachrichten',
  getParentRoute: () => rootRouteImport,
} as any)
const MerklisteRoute = MerklisteRouteImport.update({
  id: '/merkliste',
  path: '/merkliste',
  getParentRoute: () => rootRouteImport,
} as any)
const MeinRadRoute = MeinRadRouteImport.update({
  id: '/mein-rad',
  path: '/mein-rad',
  getParentRoute: () => rootRouteImport,
} as any)
const MediadatenRoute = MediadatenRouteImport.update({
  id: '/mediadaten',
  path: '/mediadaten',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KarteRoute = KarteRouteImport.update({
  id: '/karte',
  path: '/karte',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritenRoute = FavoritenRouteImport.update({
  id: '/favoriten',
  path: '/favoriten',
  getParentRoute: () => rootRouteImport,
} as any)
const FahrraederRoute = FahrraederRouteImport.update({
  id: '/fahrraeder',
  path: '/fahrraeder',
  getParentRoute: () => rootRouteImport,
} as any)
const EBikesRoute = EBikesRouteImport.update({
  id: '/e-bikes',
  path: '/e-bikes',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const BildnachweiseRoute = BildnachweiseRouteImport.update({
  id: '/bildnachweise',
  path: '/bildnachweise',
  getParentRoute: () => rootRouteImport,
} as any)
const BarrierefreiheitRoute = BarrierefreiheitRouteImport.update({
  id: '/barrierefreiheit',
  path: '/barrierefreiheit',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsWerkzeugListeRoute = ToolsWerkzeugListeRouteImport.update({
  id: '/werkzeug-liste',
  path: '/werkzeug-liste',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsWartungsintervalleRoute = ToolsWartungsintervalleRouteImport.update({
  id: '/wartungsintervalle',
  path: '/wartungsintervalle',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsVersicherungRoute = ToolsVersicherungRouteImport.update({
  id: '/versicherung',
  path: '/versicherung',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsVergleichRoute = ToolsVergleichRouteImport.update({
  id: '/vergleich',
  path: '/vergleich',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsUebersetzungRechnerRoute =
  ToolsUebersetzungRechnerRouteImport.update({
    id: '/uebersetzung-rechner',
    path: '/uebersetzung-rechner',
    getParentRoute: () => ToolsRoute,
  } as any)
const ToolsUebersetzungRoute = ToolsUebersetzungRouteImport.update({
  id: '/uebersetzung',
  path: '/uebersetzung',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsTourenplanerRoute = ToolsTourenplanerRouteImport.update({
  id: '/tourenplaner',
  path: '/tourenplaner',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsStvoRoute = ToolsStvoRouteImport.update({
  id: '/stvo',
  path: '/stvo',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsSonnenzeitenRoute = ToolsSonnenzeitenRouteImport.update({
  id: '/sonnenzeiten',
  path: '/sonnenzeiten',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsSicherheitsCheckRoute = ToolsSicherheitsCheckRouteImport.update({
  id: '/sicherheits-check',
  path: '/sicherheits-check',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsReifendruckRechnerRoute = ToolsReifendruckRechnerRouteImport.update({
  id: '/reifendruck-rechner',
  path: '/reifendruck-rechner',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsReifendruckRoute = ToolsReifendruckRouteImport.update({
  id: '/reifendruck',
  path: '/reifendruck',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsRahmengroessenRechnerRoute =
  ToolsRahmengroessenRechnerRouteImport.update({
    id: '/rahmengroessen-rechner',
    path: '/rahmengroessen-rechner',
    getParentRoute: () => ToolsRoute,
  } as any)
const ToolsRahmengroesseRoute = ToolsRahmengroesseRouteImport.update({
  id: '/rahmengroesse',
  path: '/rahmengroesse',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsRadelScoreGuideRoute = ToolsRadelScoreGuideRouteImport.update({
  id: '/radel-score-guide',
  path: '/radel-score-guide',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsRadelScoreRoute = ToolsRadelScoreRouteImport.update({
  id: '/radel-score',
  path: '/radel-score',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsPannenhilfeRoute = ToolsPannenhilfeRouteImport.update({
  id: '/pannenhilfe',
  path: '/pannenhilfe',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsLuftqualitaetRoute = ToolsLuftqualitaetRouteImport.update({
  id: '/luftqualitaet',
  path: '/luftqualitaet',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsKaufberaterAiRoute = ToolsKaufberaterAiRouteImport.update({
  id: '/kaufberater-ai',
  path: '/kaufberater-ai',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsKaufberaterRoute = ToolsKaufberaterRouteImport.update({
  id: '/kaufberater',
  path: '/kaufberater',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsKalorienRechnerRoute = ToolsKalorienRechnerRouteImport.update({
  id: '/kalorien-rechner',
  path: '/kalorien-rechner',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsKalorienRoute = ToolsKalorienRouteImport.update({
  id: '/kalorien',
  path: '/kalorien',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsJobradLeasingRechnerRoute =
  ToolsJobradLeasingRechnerRouteImport.update({
    id: '/jobrad-leasing-rechner',
    path: '/jobrad-leasing-rechner',
    getParentRoute: () => ToolsRoute,
  } as any)
const ToolsJobradLeasingRoute = ToolsJobradLeasingRouteImport.update({
  id: '/jobrad-leasing',
  path: '/jobrad-leasing',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsFoerderungRoute = ToolsFoerderungRouteImport.update({
  id: '/foerderung',
  path: '/foerderung',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsFahrradWetterRoute = ToolsFahrradWetterRouteImport.update({
  id: '/fahrrad-wetter',
  path: '/fahrrad-wetter',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsFahrradVergleichRoute = ToolsFahrradVergleichRouteImport.update({
  id: '/fahrrad-vergleich',
  path: '/fahrrad-vergleich',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsEcoRouteRoute = ToolsEcoRouteRouteImport.update({
  id: '/eco-route',
  path: '/eco-route',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsEbikeReichweiteRechnerRoute =
  ToolsEbikeReichweiteRechnerRouteImport.update({
    id: '/ebike-reichweite-rechner',
    path: '/ebike-reichweite-rechner',
    getParentRoute: () => ToolsRoute,
  } as any)
const ToolsEbikeReichweiteRoute = ToolsEbikeReichweiteRouteImport.update({
  id: '/ebike-reichweite',
  path: '/ebike-reichweite',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsEbikeFoerderungRechnerRoute =
  ToolsEbikeFoerderungRechnerRouteImport.update({
    id: '/ebike-foerderung-rechner',
    path: '/ebike-foerderung-rechner',
    getParentRoute: () => ToolsRoute,
  } as any)
const ToolsDiebstahlschutzRoute = ToolsDiebstahlschutzRouteImport.update({
  id: '/diebstahlschutz',
  path: '/diebstahlschutz',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsBussgeldRoute = ToolsBussgeldRouteImport.update({
  id: '/bussgeld',
  path: '/bussgeld',
  getParentRoute: () => ToolsRoute,
} as any)
const NewsletterBestaetigenRoute = NewsletterBestaetigenRouteImport.update({
  id: '/newsletter/bestaetigen',
  path: '/newsletter/bestaetigen',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterAbmeldenRoute = NewsletterAbmeldenRouteImport.update({
  id: '/newsletter/abmelden',
  path: '/newsletter/abmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const FahrraederSlugRoute = FahrraederSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FahrraederRoute,
} as any)
const ArtikelSlugRoute = ArtikelSlugRouteImport.update({
  id: '/artikel/$slug',
  path: '/artikel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMnvRoute = AuthenticatedMnvRouteImport.update({
  id: '/mnv',
  path: '/mnv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMnvIndexRoute = AuthenticatedMnvIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMnvRoute,
} as any)
const AuthenticatedMnvUsersRoute = AuthenticatedMnvUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedMnvRoute,
} as any)
const AuthenticatedMnvNewsletterRoute =
  AuthenticatedMnvNewsletterRouteImport.update({
    id: '/newsletter',
    path: '/newsletter',
    getParentRoute: () => AuthenticatedMnvRoute,
  } as any)
const AuthenticatedMnvMessagesRoute =
  AuthenticatedMnvMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedMnvRoute,
  } as any)
const AuthenticatedMnvMediaRoute = AuthenticatedMnvMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedMnvRoute,
} as any)
const AuthenticatedMnvBikesRoute = AuthenticatedMnvBikesRouteImport.update({
  id: '/bikes',
  path: '/bikes',
  getParentRoute: () => AuthenticatedMnvRoute,
} as any)
const AuthenticatedMnvAutoArticlesRoute =
  AuthenticatedMnvAutoArticlesRouteImport.update({
    id: '/auto-articles',
    path: '/auto-articles',
    getParentRoute: () => AuthenticatedMnvRoute,
  } as any)
const AuthenticatedMnvArticlesRoute =
  AuthenticatedMnvArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AuthenticatedMnvRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNewsletterUnsubscribeRoute =
  ApiPublicNewsletterUnsubscribeRouteImport.update({
    id: '/api/public/newsletter/unsubscribe',
    path: '/api/public/newsletter/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNewsletterDispatchRoute =
  ApiPublicNewsletterDispatchRouteImport.update({
    id: '/api/public/newsletter/dispatch',
    path: '/api/public/newsletter/dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicArticlesAutoGenerateRoute =
  ApiPublicArticlesAutoGenerateRouteImport.update({
    id: '/api/public/articles/auto-generate',
    path: '/api/public/articles/auto-generate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicArticleImagePathRoute =
  ApiPublicArticleImagePathRouteImport.update({
    id: '/api/public/article-image/$path',
    path: '/api/public/article-image/$path',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMnvBikesNewRoute =
  AuthenticatedMnvBikesNewRouteImport.update({
    id: '/bikes_/new',
    path: '/bikes/new',
    getParentRoute: () => AuthenticatedMnvRoute,
  } as any)
const AuthenticatedMnvBikesIdRoute = AuthenticatedMnvBikesIdRouteImport.update({
  id: '/bikes_/$id',
  path: '/bikes/$id',
  getParentRoute: () => AuthenticatedMnvRoute,
} as any)
const AuthenticatedMnvArticlesNewRoute =
  AuthenticatedMnvArticlesNewRouteImport.update({
    id: '/articles_/new',
    path: '/articles/new',
    getParentRoute: () => AuthenticatedMnvRoute,
  } as any)
const AuthenticatedMnvArticlesIdRoute =
  AuthenticatedMnvArticlesIdRouteImport.update({
    id: '/articles_/$id',
    path: '/articles/$id',
    getParentRoute: () => AuthenticatedMnvRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/barrierefreiheit': typeof BarrierefreiheitRoute
  '/bildnachweise': typeof BildnachweiseRoute
  '/cookies': typeof CookiesRoute
  '/datenschutz': typeof DatenschutzRoute
  '/e-bikes': typeof EBikesRoute
  '/fahrraeder': typeof FahrraederRouteWithChildren
  '/favoriten': typeof FavoritenRoute
  '/impressum': typeof ImpressumRoute
  '/karte': typeof KarteRoute
  '/kontakt': typeof KontaktRoute
  '/mediadaten': typeof MediadatenRoute
  '/mein-rad': typeof MeinRadRoute
  '/merkliste': typeof MerklisteRoute
  '/nachrichten': typeof NachrichtenRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/nutzungsbedingungen': typeof NutzungsbedingungenRoute
  '/passt-zu-dir': typeof PasstZuDirRoute
  '/ratgeber': typeof RatgeberRoute
  '/redaktion': typeof RedaktionRoute
  '/sicherheit': typeof SicherheitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tests': typeof TestsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/ueber-uns': typeof UeberUnsRoute
  '/vergleich': typeof VergleichRoute
  '/mnv': typeof AuthenticatedMnvRouteWithChildren
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/fahrraeder/$slug': typeof FahrraederSlugRoute
  '/newsletter/abmelden': typeof NewsletterAbmeldenRoute
  '/newsletter/bestaetigen': typeof NewsletterBestaetigenRoute
  '/tools/bussgeld': typeof ToolsBussgeldRoute
  '/tools/diebstahlschutz': typeof ToolsDiebstahlschutzRoute
  '/tools/ebike-foerderung-rechner': typeof ToolsEbikeFoerderungRechnerRoute
  '/tools/ebike-reichweite': typeof ToolsEbikeReichweiteRoute
  '/tools/ebike-reichweite-rechner': typeof ToolsEbikeReichweiteRechnerRoute
  '/tools/eco-route': typeof ToolsEcoRouteRoute
  '/tools/fahrrad-vergleich': typeof ToolsFahrradVergleichRoute
  '/tools/fahrrad-wetter': typeof ToolsFahrradWetterRoute
  '/tools/foerderung': typeof ToolsFoerderungRoute
  '/tools/jobrad-leasing': typeof ToolsJobradLeasingRoute
  '/tools/jobrad-leasing-rechner': typeof ToolsJobradLeasingRechnerRoute
  '/tools/kalorien': typeof ToolsKalorienRoute
  '/tools/kalorien-rechner': typeof ToolsKalorienRechnerRoute
  '/tools/kaufberater': typeof ToolsKaufberaterRoute
  '/tools/kaufberater-ai': typeof ToolsKaufberaterAiRoute
  '/tools/luftqualitaet': typeof ToolsLuftqualitaetRoute
  '/tools/pannenhilfe': typeof ToolsPannenhilfeRoute
  '/tools/radel-score': typeof ToolsRadelScoreRoute
  '/tools/radel-score-guide': typeof ToolsRadelScoreGuideRoute
  '/tools/rahmengroesse': typeof ToolsRahmengroesseRoute
  '/tools/rahmengroessen-rechner': typeof ToolsRahmengroessenRechnerRoute
  '/tools/reifendruck': typeof ToolsReifendruckRoute
  '/tools/reifendruck-rechner': typeof ToolsReifendruckRechnerRoute
  '/tools/sicherheits-check': typeof ToolsSicherheitsCheckRoute
  '/tools/sonnenzeiten': typeof ToolsSonnenzeitenRoute
  '/tools/stvo': typeof ToolsStvoRoute
  '/tools/tourenplaner': typeof ToolsTourenplanerRoute
  '/tools/uebersetzung': typeof ToolsUebersetzungRoute
  '/tools/uebersetzung-rechner': typeof ToolsUebersetzungRechnerRoute
  '/tools/vergleich': typeof ToolsVergleichRoute
  '/tools/versicherung': typeof ToolsVersicherungRoute
  '/tools/wartungsintervalle': typeof ToolsWartungsintervalleRoute
  '/tools/werkzeug-liste': typeof ToolsWerkzeugListeRoute
  '/tools/': typeof ToolsIndexRoute
  '/mnv/articles': typeof AuthenticatedMnvArticlesRoute
  '/mnv/auto-articles': typeof AuthenticatedMnvAutoArticlesRoute
  '/mnv/bikes': typeof AuthenticatedMnvBikesRoute
  '/mnv/media': typeof AuthenticatedMnvMediaRoute
  '/mnv/messages': typeof AuthenticatedMnvMessagesRoute
  '/mnv/newsletter': typeof AuthenticatedMnvNewsletterRoute
  '/mnv/users': typeof AuthenticatedMnvUsersRoute
  '/mnv/': typeof AuthenticatedMnvIndexRoute
  '/mnv/articles/$id': typeof AuthenticatedMnvArticlesIdRoute
  '/mnv/articles/new': typeof AuthenticatedMnvArticlesNewRoute
  '/mnv/bikes/$id': typeof AuthenticatedMnvBikesIdRoute
  '/mnv/bikes/new': typeof AuthenticatedMnvBikesNewRoute
  '/api/public/article-image/$path': typeof ApiPublicArticleImagePathRoute
  '/api/public/articles/auto-generate': typeof ApiPublicArticlesAutoGenerateRoute
  '/api/public/newsletter/dispatch': typeof ApiPublicNewsletterDispatchRoute
  '/api/public/newsletter/unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/barrierefreiheit': typeof BarrierefreiheitRoute
  '/bildnachweise': typeof BildnachweiseRoute
  '/cookies': typeof CookiesRoute
  '/datenschutz': typeof DatenschutzRoute
  '/e-bikes': typeof EBikesRoute
  '/fahrraeder': typeof FahrraederRouteWithChildren
  '/favoriten': typeof FavoritenRoute
  '/impressum': typeof ImpressumRoute
  '/karte': typeof KarteRoute
  '/kontakt': typeof KontaktRoute
  '/mediadaten': typeof MediadatenRoute
  '/mein-rad': typeof MeinRadRoute
  '/merkliste': typeof MerklisteRoute
  '/nachrichten': typeof NachrichtenRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/nutzungsbedingungen': typeof NutzungsbedingungenRoute
  '/passt-zu-dir': typeof PasstZuDirRoute
  '/ratgeber': typeof RatgeberRoute
  '/redaktion': typeof RedaktionRoute
  '/sicherheit': typeof SicherheitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tests': typeof TestsRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/vergleich': typeof VergleichRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/fahrraeder/$slug': typeof FahrraederSlugRoute
  '/newsletter/abmelden': typeof NewsletterAbmeldenRoute
  '/newsletter/bestaetigen': typeof NewsletterBestaetigenRoute
  '/tools/bussgeld': typeof ToolsBussgeldRoute
  '/tools/diebstahlschutz': typeof ToolsDiebstahlschutzRoute
  '/tools/ebike-foerderung-rechner': typeof ToolsEbikeFoerderungRechnerRoute
  '/tools/ebike-reichweite': typeof ToolsEbikeReichweiteRoute
  '/tools/ebike-reichweite-rechner': typeof ToolsEbikeReichweiteRechnerRoute
  '/tools/eco-route': typeof ToolsEcoRouteRoute
  '/tools/fahrrad-vergleich': typeof ToolsFahrradVergleichRoute
  '/tools/fahrrad-wetter': typeof ToolsFahrradWetterRoute
  '/tools/foerderung': typeof ToolsFoerderungRoute
  '/tools/jobrad-leasing': typeof ToolsJobradLeasingRoute
  '/tools/jobrad-leasing-rechner': typeof ToolsJobradLeasingRechnerRoute
  '/tools/kalorien': typeof ToolsKalorienRoute
  '/tools/kalorien-rechner': typeof ToolsKalorienRechnerRoute
  '/tools/kaufberater': typeof ToolsKaufberaterRoute
  '/tools/kaufberater-ai': typeof ToolsKaufberaterAiRoute
  '/tools/luftqualitaet': typeof ToolsLuftqualitaetRoute
  '/tools/pannenhilfe': typeof ToolsPannenhilfeRoute
  '/tools/radel-score': typeof ToolsRadelScoreRoute
  '/tools/radel-score-guide': typeof ToolsRadelScoreGuideRoute
  '/tools/rahmengroesse': typeof ToolsRahmengroesseRoute
  '/tools/rahmengroessen-rechner': typeof ToolsRahmengroessenRechnerRoute
  '/tools/reifendruck': typeof ToolsReifendruckRoute
  '/tools/reifendruck-rechner': typeof ToolsReifendruckRechnerRoute
  '/tools/sicherheits-check': typeof ToolsSicherheitsCheckRoute
  '/tools/sonnenzeiten': typeof ToolsSonnenzeitenRoute
  '/tools/stvo': typeof ToolsStvoRoute
  '/tools/tourenplaner': typeof ToolsTourenplanerRoute
  '/tools/uebersetzung': typeof ToolsUebersetzungRoute
  '/tools/uebersetzung-rechner': typeof ToolsUebersetzungRechnerRoute
  '/tools/vergleich': typeof ToolsVergleichRoute
  '/tools/versicherung': typeof ToolsVersicherungRoute
  '/tools/wartungsintervalle': typeof ToolsWartungsintervalleRoute
  '/tools/werkzeug-liste': typeof ToolsWerkzeugListeRoute
  '/tools': typeof ToolsIndexRoute
  '/mnv/articles': typeof AuthenticatedMnvArticlesRoute
  '/mnv/auto-articles': typeof AuthenticatedMnvAutoArticlesRoute
  '/mnv/bikes': typeof AuthenticatedMnvBikesRoute
  '/mnv/media': typeof AuthenticatedMnvMediaRoute
  '/mnv/messages': typeof AuthenticatedMnvMessagesRoute
  '/mnv/newsletter': typeof AuthenticatedMnvNewsletterRoute
  '/mnv/users': typeof AuthenticatedMnvUsersRoute
  '/mnv': typeof AuthenticatedMnvIndexRoute
  '/mnv/articles/$id': typeof AuthenticatedMnvArticlesIdRoute
  '/mnv/articles/new': typeof AuthenticatedMnvArticlesNewRoute
  '/mnv/bikes/$id': typeof AuthenticatedMnvBikesIdRoute
  '/mnv/bikes/new': typeof AuthenticatedMnvBikesNewRoute
  '/api/public/article-image/$path': typeof ApiPublicArticleImagePathRoute
  '/api/public/articles/auto-generate': typeof ApiPublicArticlesAutoGenerateRoute
  '/api/public/newsletter/dispatch': typeof ApiPublicNewsletterDispatchRoute
  '/api/public/newsletter/unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agb': typeof AgbRoute
  '/barrierefreiheit': typeof BarrierefreiheitRoute
  '/bildnachweise': typeof BildnachweiseRoute
  '/cookies': typeof CookiesRoute
  '/datenschutz': typeof DatenschutzRoute
  '/e-bikes': typeof EBikesRoute
  '/fahrraeder': typeof FahrraederRouteWithChildren
  '/favoriten': typeof FavoritenRoute
  '/impressum': typeof ImpressumRoute
  '/karte': typeof KarteRoute
  '/kontakt': typeof KontaktRoute
  '/mediadaten': typeof MediadatenRoute
  '/mein-rad': typeof MeinRadRoute
  '/merkliste': typeof MerklisteRoute
  '/nachrichten': typeof NachrichtenRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/nutzungsbedingungen': typeof NutzungsbedingungenRoute
  '/passt-zu-dir': typeof PasstZuDirRoute
  '/ratgeber': typeof RatgeberRoute
  '/redaktion': typeof RedaktionRoute
  '/sicherheit': typeof SicherheitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tests': typeof TestsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/ueber-uns': typeof UeberUnsRoute
  '/vergleich': typeof VergleichRoute
  '/_authenticated/mnv': typeof AuthenticatedMnvRouteWithChildren
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/fahrraeder/$slug': typeof FahrraederSlugRoute
  '/newsletter/abmelden': typeof NewsletterAbmeldenRoute
  '/newsletter/bestaetigen': typeof NewsletterBestaetigenRoute
  '/tools/bussgeld': typeof ToolsBussgeldRoute
  '/tools/diebstahlschutz': typeof ToolsDiebstahlschutzRoute
  '/tools/ebike-foerderung-rechner': typeof ToolsEbikeFoerderungRechnerRoute
  '/tools/ebike-reichweite': typeof ToolsEbikeReichweiteRoute
  '/tools/ebike-reichweite-rechner': typeof ToolsEbikeReichweiteRechnerRoute
  '/tools/eco-route': typeof ToolsEcoRouteRoute
  '/tools/fahrrad-vergleich': typeof ToolsFahrradVergleichRoute
  '/tools/fahrrad-wetter': typeof ToolsFahrradWetterRoute
  '/tools/foerderung': typeof ToolsFoerderungRoute
  '/tools/jobrad-leasing': typeof ToolsJobradLeasingRoute
  '/tools/jobrad-leasing-rechner': typeof ToolsJobradLeasingRechnerRoute
  '/tools/kalorien': typeof ToolsKalorienRoute
  '/tools/kalorien-rechner': typeof ToolsKalorienRechnerRoute
  '/tools/kaufberater': typeof ToolsKaufberaterRoute
  '/tools/kaufberater-ai': typeof ToolsKaufberaterAiRoute
  '/tools/luftqualitaet': typeof ToolsLuftqualitaetRoute
  '/tools/pannenhilfe': typeof ToolsPannenhilfeRoute
  '/tools/radel-score': typeof ToolsRadelScoreRoute
  '/tools/radel-score-guide': typeof ToolsRadelScoreGuideRoute
  '/tools/rahmengroesse': typeof ToolsRahmengroesseRoute
  '/tools/rahmengroessen-rechner': typeof ToolsRahmengroessenRechnerRoute
  '/tools/reifendruck': typeof ToolsReifendruckRoute
  '/tools/reifendruck-rechner': typeof ToolsReifendruckRechnerRoute
  '/tools/sicherheits-check': typeof ToolsSicherheitsCheckRoute
  '/tools/sonnenzeiten': typeof ToolsSonnenzeitenRoute
  '/tools/stvo': typeof ToolsStvoRoute
  '/tools/tourenplaner': typeof ToolsTourenplanerRoute
  '/tools/uebersetzung': typeof ToolsUebersetzungRoute
  '/tools/uebersetzung-rechner': typeof ToolsUebersetzungRechnerRoute
  '/tools/vergleich': typeof ToolsVergleichRoute
  '/tools/versicherung': typeof ToolsVersicherungRoute
  '/tools/wartungsintervalle': typeof ToolsWartungsintervalleRoute
  '/tools/werkzeug-liste': typeof ToolsWerkzeugListeRoute
  '/tools/': typeof ToolsIndexRoute
  '/_authenticated/mnv/articles': typeof AuthenticatedMnvArticlesRoute
  '/_authenticated/mnv/auto-articles': typeof AuthenticatedMnvAutoArticlesRoute
  '/_authenticated/mnv/bikes': typeof AuthenticatedMnvBikesRoute
  '/_authenticated/mnv/media': typeof AuthenticatedMnvMediaRoute
  '/_authenticated/mnv/messages': typeof AuthenticatedMnvMessagesRoute
  '/_authenticated/mnv/newsletter': typeof AuthenticatedMnvNewsletterRoute
  '/_authenticated/mnv/users': typeof AuthenticatedMnvUsersRoute
  '/_authenticated/mnv/': typeof AuthenticatedMnvIndexRoute
  '/_authenticated/mnv/articles_/$id': typeof AuthenticatedMnvArticlesIdRoute
  '/_authenticated/mnv/articles_/new': typeof AuthenticatedMnvArticlesNewRoute
  '/_authenticated/mnv/bikes_/$id': typeof AuthenticatedMnvBikesIdRoute
  '/_authenticated/mnv/bikes_/new': typeof AuthenticatedMnvBikesNewRoute
  '/api/public/article-image/$path': typeof ApiPublicArticleImagePathRoute
  '/api/public/articles/auto-generate': typeof ApiPublicArticlesAutoGenerateRoute
  '/api/public/newsletter/dispatch': typeof ApiPublicNewsletterDispatchRoute
  '/api/public/newsletter/unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/barrierefreiheit'
    | '/bildnachweise'
    | '/cookies'
    | '/datenschutz'
    | '/e-bikes'
    | '/fahrraeder'
    | '/favoriten'
    | '/impressum'
    | '/karte'
    | '/kontakt'
    | '/mediadaten'
    | '/mein-rad'
    | '/merkliste'
    | '/nachrichten'
    | '/news-sitemap.xml'
    | '/nutzungsbedingungen'
    | '/passt-zu-dir'
    | '/ratgeber'
    | '/redaktion'
    | '/sicherheit'
    | '/sitemap.xml'
    | '/tests'
    | '/tools'
    | '/ueber-uns'
    | '/vergleich'
    | '/mnv'
    | '/artikel/$slug'
    | '/fahrraeder/$slug'
    | '/newsletter/abmelden'
    | '/newsletter/bestaetigen'
    | '/tools/bussgeld'
    | '/tools/diebstahlschutz'
    | '/tools/ebike-foerderung-rechner'
    | '/tools/ebike-reichweite'
    | '/tools/ebike-reichweite-rechner'
    | '/tools/eco-route'
    | '/tools/fahrrad-vergleich'
    | '/tools/fahrrad-wetter'
    | '/tools/foerderung'
    | '/tools/jobrad-leasing'
    | '/tools/jobrad-leasing-rechner'
    | '/tools/kalorien'
    | '/tools/kalorien-rechner'
    | '/tools/kaufberater'
    | '/tools/kaufberater-ai'
    | '/tools/luftqualitaet'
    | '/tools/pannenhilfe'
    | '/tools/radel-score'
    | '/tools/radel-score-guide'
    | '/tools/rahmengroesse'
    | '/tools/rahmengroessen-rechner'
    | '/tools/reifendruck'
    | '/tools/reifendruck-rechner'
    | '/tools/sicherheits-check'
    | '/tools/sonnenzeiten'
    | '/tools/stvo'
    | '/tools/tourenplaner'
    | '/tools/uebersetzung'
    | '/tools/uebersetzung-rechner'
    | '/tools/vergleich'
    | '/tools/versicherung'
    | '/tools/wartungsintervalle'
    | '/tools/werkzeug-liste'
    | '/tools/'
    | '/mnv/articles'
    | '/mnv/auto-articles'
    | '/mnv/bikes'
    | '/mnv/media'
    | '/mnv/messages'
    | '/mnv/newsletter'
    | '/mnv/users'
    | '/mnv/'
    | '/mnv/articles/$id'
    | '/mnv/articles/new'
    | '/mnv/bikes/$id'
    | '/mnv/bikes/new'
    | '/api/public/article-image/$path'
    | '/api/public/articles/auto-generate'
    | '/api/public/newsletter/dispatch'
    | '/api/public/newsletter/unsubscribe'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/barrierefreiheit'
    | '/bildnachweise'
    | '/cookies'
    | '/datenschutz'
    | '/e-bikes'
    | '/fahrraeder'
    | '/favoriten'
    | '/impressum'
    | '/karte'
    | '/kontakt'
    | '/mediadaten'
    | '/mein-rad'
    | '/merkliste'
    | '/nachrichten'
    | '/news-sitemap.xml'
    | '/nutzungsbedingungen'
    | '/passt-zu-dir'
    | '/ratgeber'
    | '/redaktion'
    | '/sicherheit'
    | '/sitemap.xml'
    | '/tests'
    | '/ueber-uns'
    | '/vergleich'
    | '/artikel/$slug'
    | '/fahrraeder/$slug'
    | '/newsletter/abmelden'
    | '/newsletter/bestaetigen'
    | '/tools/bussgeld'
    | '/tools/diebstahlschutz'
    | '/tools/ebike-foerderung-rechner'
    | '/tools/ebike-reichweite'
    | '/tools/ebike-reichweite-rechner'
    | '/tools/eco-route'
    | '/tools/fahrrad-vergleich'
    | '/tools/fahrrad-wetter'
    | '/tools/foerderung'
    | '/tools/jobrad-leasing'
    | '/tools/jobrad-leasing-rechner'
    | '/tools/kalorien'
    | '/tools/kalorien-rechner'
    | '/tools/kaufberater'
    | '/tools/kaufberater-ai'
    | '/tools/luftqualitaet'
    | '/tools/pannenhilfe'
    | '/tools/radel-score'
    | '/tools/radel-score-guide'
    | '/tools/rahmengroesse'
    | '/tools/rahmengroessen-rechner'
    | '/tools/reifendruck'
    | '/tools/reifendruck-rechner'
    | '/tools/sicherheits-check'
    | '/tools/sonnenzeiten'
    | '/tools/stvo'
    | '/tools/tourenplaner'
    | '/tools/uebersetzung'
    | '/tools/uebersetzung-rechner'
    | '/tools/vergleich'
    | '/tools/versicherung'
    | '/tools/wartungsintervalle'
    | '/tools/werkzeug-liste'
    | '/tools'
    | '/mnv/articles'
    | '/mnv/auto-articles'
    | '/mnv/bikes'
    | '/mnv/media'
    | '/mnv/messages'
    | '/mnv/newsletter'
    | '/mnv/users'
    | '/mnv'
    | '/mnv/articles/$id'
    | '/mnv/articles/new'
    | '/mnv/bikes/$id'
    | '/mnv/bikes/new'
    | '/api/public/article-image/$path'
    | '/api/public/articles/auto-generate'
    | '/api/public/newsletter/dispatch'
    | '/api/public/newsletter/unsubscribe'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agb'
    | '/barrierefreiheit'
    | '/bildnachweise'
    | '/cookies'
    | '/datenschutz'
    | '/e-bikes'
    | '/fahrraeder'
    | '/favoriten'
    | '/impressum'
    | '/karte'
    | '/kontakt'
    | '/mediadaten'
    | '/mein-rad'
    | '/merkliste'
    | '/nachrichten'
    | '/news-sitemap.xml'
    | '/nutzungsbedingungen'
    | '/passt-zu-dir'
    | '/ratgeber'
    | '/redaktion'
    | '/sicherheit'
    | '/sitemap.xml'
    | '/tests'
    | '/tools'
    | '/ueber-uns'
    | '/vergleich'
    | '/_authenticated/mnv'
    | '/artikel/$slug'
    | '/fahrraeder/$slug'
    | '/newsletter/abmelden'
    | '/newsletter/bestaetigen'
    | '/tools/bussgeld'
    | '/tools/diebstahlschutz'
    | '/tools/ebike-foerderung-rechner'
    | '/tools/ebike-reichweite'
    | '/tools/ebike-reichweite-rechner'
    | '/tools/eco-route'
    | '/tools/fahrrad-vergleich'
    | '/tools/fahrrad-wetter'
    | '/tools/foerderung'
    | '/tools/jobrad-leasing'
    | '/tools/jobrad-leasing-rechner'
    | '/tools/kalorien'
    | '/tools/kalorien-rechner'
    | '/tools/kaufberater'
    | '/tools/kaufberater-ai'
    | '/tools/luftqualitaet'
    | '/tools/pannenhilfe'
    | '/tools/radel-score'
    | '/tools/radel-score-guide'
    | '/tools/rahmengroesse'
    | '/tools/rahmengroessen-rechner'
    | '/tools/reifendruck'
    | '/tools/reifendruck-rechner'
    | '/tools/sicherheits-check'
    | '/tools/sonnenzeiten'
    | '/tools/stvo'
    | '/tools/tourenplaner'
    | '/tools/uebersetzung'
    | '/tools/uebersetzung-rechner'
    | '/tools/vergleich'
    | '/tools/versicherung'
    | '/tools/wartungsintervalle'
    | '/tools/werkzeug-liste'
    | '/tools/'
    | '/_authenticated/mnv/articles'
    | '/_authenticated/mnv/auto-articles'
    | '/_authenticated/mnv/bikes'
    | '/_authenticated/mnv/media'
    | '/_authenticated/mnv/messages'
    | '/_authenticated/mnv/newsletter'
    | '/_authenticated/mnv/users'
    | '/_authenticated/mnv/'
    | '/_authenticated/mnv/articles_/$id'
    | '/_authenticated/mnv/articles_/new'
    | '/_authenticated/mnv/bikes_/$id'
    | '/_authenticated/mnv/bikes_/new'
    | '/api/public/article-image/$path'
    | '/api/public/articles/auto-generate'
    | '/api/public/newsletter/dispatch'
    | '/api/public/newsletter/unsubscribe'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgbRoute: typeof AgbRoute
  BarrierefreiheitRoute: typeof BarrierefreiheitRoute
  BildnachweiseRoute: typeof BildnachweiseRoute
  CookiesRoute: typeof CookiesRoute
  DatenschutzRoute: typeof DatenschutzRoute
  EBikesRoute: typeof EBikesRoute
  FahrraederRoute: typeof FahrraederRouteWithChildren
  FavoritenRoute: typeof FavoritenRoute
  ImpressumRoute: typeof ImpressumRoute
  KarteRoute: typeof KarteRoute
  KontaktRoute: typeof KontaktRoute
  MediadatenRoute: typeof MediadatenRoute
  MeinRadRoute: typeof MeinRadRoute
  MerklisteRoute: typeof MerklisteRoute
  NachrichtenRoute: typeof NachrichtenRoute
  NewsSitemapDotxmlRoute: typeof NewsSitemapDotxmlRoute
  NutzungsbedingungenRoute: typeof NutzungsbedingungenRoute
  PasstZuDirRoute: typeof PasstZuDirRoute
  RatgeberRoute: typeof RatgeberRoute
  RedaktionRoute: typeof RedaktionRoute
  SicherheitRoute: typeof SicherheitRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestsRoute: typeof TestsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  UeberUnsRoute: typeof UeberUnsRoute
  VergleichRoute: typeof VergleichRoute
  ArtikelSlugRoute: typeof ArtikelSlugRoute
  NewsletterAbmeldenRoute: typeof NewsletterAbmeldenRoute
  NewsletterBestaetigenRoute: typeof NewsletterBestaetigenRoute
  ApiPublicArticleImagePathRoute: typeof ApiPublicArticleImagePathRoute
  ApiPublicArticlesAutoGenerateRoute: typeof ApiPublicArticlesAutoGenerateRoute
  ApiPublicNewsletterDispatchRoute: typeof ApiPublicNewsletterDispatchRoute
  ApiPublicNewsletterUnsubscribeRoute: typeof ApiPublicNewsletterUnsubscribeRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vergleich': {
      id: '/vergleich'
      path: '/vergleich'
      fullPath: '/vergleich'
      preLoaderRoute: typeof VergleichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sicherheit': {
      id: '/sicherheit'
      path: '/sicherheit'
      fullPath: '/sicherheit'
      preLoaderRoute: typeof SicherheitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redaktion': {
      id: '/redaktion'
      path: '/redaktion'
      fullPath: '/redaktion'
      preLoaderRoute: typeof RedaktionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber': {
      id: '/ratgeber'
      path: '/ratgeber'
      fullPath: '/ratgeber'
      preLoaderRoute: typeof RatgeberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passt-zu-dir': {
      id: '/passt-zu-dir'
      path: '/passt-zu-dir'
      fullPath: '/passt-zu-dir'
      preLoaderRoute: typeof PasstZuDirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutzungsbedingungen': {
      id: '/nutzungsbedingungen'
      path: '/nutzungsbedingungen'
      fullPath: '/nutzungsbedingungen'
      preLoaderRoute: typeof NutzungsbedingungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-sitemap.xml': {
      id: '/news-sitemap.xml'
      path: '/news-sitemap.xml'
      fullPath: '/news-sitemap.xml'
      preLoaderRoute: typeof NewsSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nachrichten': {
      id: '/nachrichten'
      path: '/nachrichten'
      fullPath: '/nachrichten'
      preLoaderRoute: typeof NachrichtenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merkliste': {
      id: '/merkliste'
      path: '/merkliste'
      fullPath: '/merkliste'
      preLoaderRoute: typeof MerklisteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mein-rad': {
      id: '/mein-rad'
      path: '/mein-rad'
      fullPath: '/mein-rad'
      preLoaderRoute: typeof MeinRadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mediadaten': {
      id: '/mediadaten'
      path: '/mediadaten'
      fullPath: '/mediadaten'
      preLoaderRoute: typeof MediadatenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karte': {
      id: '/karte'
      path: '/karte'
      fullPath: '/karte'
      preLoaderRoute: typeof KarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoriten': {
      id: '/favoriten'
      path: '/favoriten'
      fullPath: '/favoriten'
      preLoaderRoute: typeof FavoritenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fahrraeder': {
      id: '/fahrraeder'
      path: '/fahrraeder'
      fullPath: '/fahrraeder'
      preLoaderRoute: typeof FahrraederRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e-bikes': {
      id: '/e-bikes'
      path: '/e-bikes'
      fullPath: '/e-bikes'
      preLoaderRoute: typeof EBikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bildnachweise': {
      id: '/bildnachweise'
      path: '/bildnachweise'
      fullPath: '/bildnachweise'
      preLoaderRoute: typeof BildnachweiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barrierefreiheit': {
      id: '/barrierefreiheit'
      path: '/barrierefreiheit'
      fullPath: '/barrierefreiheit'
      preLoaderRoute: typeof BarrierefreiheitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/werkzeug-liste': {
      id: '/tools/werkzeug-liste'
      path: '/werkzeug-liste'
      fullPath: '/tools/werkzeug-liste'
      preLoaderRoute: typeof ToolsWerkzeugListeRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/wartungsintervalle': {
      id: '/tools/wartungsintervalle'
      path: '/wartungsintervalle'
      fullPath: '/tools/wartungsintervalle'
      preLoaderRoute: typeof ToolsWartungsintervalleRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/versicherung': {
      id: '/tools/versicherung'
      path: '/versicherung'
      fullPath: '/tools/versicherung'
      preLoaderRoute: typeof ToolsVersicherungRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/vergleich': {
      id: '/tools/vergleich'
      path: '/vergleich'
      fullPath: '/tools/vergleich'
      preLoaderRoute: typeof ToolsVergleichRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/uebersetzung-rechner': {
      id: '/tools/uebersetzung-rechner'
      path: '/uebersetzung-rechner'
      fullPath: '/tools/uebersetzung-rechner'
      preLoaderRoute: typeof ToolsUebersetzungRechnerRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/uebersetzung': {
      id: '/tools/uebersetzung'
      path: '/uebersetzung'
      fullPath: '/tools/uebersetzung'
      preLoaderRoute: typeof ToolsUebersetzungRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/tourenplaner': {
      id: '/tools/tourenplaner'
      path: '/tourenplaner'
      fullPath: '/tools/tourenplaner'
      preLoaderRoute: typeof ToolsTourenplanerRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/stvo': {
      id: '/tools/stvo'
      path: '/stvo'
      fullPath: '/tools/stvo'
      preLoaderRoute: typeof ToolsStvoRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/sonnenzeiten': {
      id: '/tools/sonnenzeiten'
      path: '/sonnenzeiten'
      fullPath: '/tools/sonnenzeiten'
      preLoaderRoute: typeof ToolsSonnenzeitenRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/sicherheits-check': {
      id: '/tools/sicherheits-check'
      path: '/sicherheits-check'
      fullPath: '/tools/sicherheits-check'
      preLoaderRoute: typeof ToolsSicherheitsCheckRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/reifendruck-rechner': {
      id: '/tools/reifendruck-rechner'
      path: '/reifendruck-rechner'
      fullPath: '/tools/reifendruck-rechner'
      preLoaderRoute: typeof ToolsReifendruckRechnerRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/reifendruck': {
      id: '/tools/reifendruck'
      path: '/reifendruck'
      fullPath: '/tools/reifendruck'
      preLoaderRoute: typeof ToolsReifendruckRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/rahmengroessen-rechner': {
      id: '/tools/rahmengroessen-rechner'
      path: '/rahmengroessen-rechner'
      fullPath: '/tools/rahmengroessen-rechner'
      preLoaderRoute: typeof ToolsRahmengroessenRechnerRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/rahmengroesse': {
      id: '/tools/rahmengroesse'
      path: '/rahmengroesse'
      fullPath: '/tools/rahmengroesse'
      preLoaderRoute: typeof ToolsRahmengroesseRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/radel-score-guide': {
      id: '/tools/radel-score-guide'
      path: '/radel-score-guide'
      fullPath: '/tools/radel-score-guide'
      preLoaderRoute: typeof ToolsRadelScoreGuideRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/radel-score': {
      id: '/tools/radel-score'
      path: '/radel-score'
      fullPath: '/tools/radel-score'
      preLoaderRoute: typeof ToolsRadelScoreRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/pannenhilfe': {
      id: '/tools/pannenhilfe'
      path: '/pannenhilfe'
      fullPath: '/tools/pannenhilfe'
      preLoaderRoute: typeof ToolsPannenhilfeRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/luftqualitaet': {
      id: '/tools/luftqualitaet'
      path: '/luftqualitaet'
      fullPath: '/tools/luftqualitaet'
      preLoaderRoute: typeof ToolsLuftqualitaetRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/kaufberater-ai': {
      id: '/tools/kaufberater-ai'
      path: '/kaufberater-ai'
      fullPath: '/tools/kaufberater-ai'
      preLoaderRoute: typeof ToolsKaufberaterAiRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/kaufberater': {
      id: '/tools/kaufberater'
      path: '/kaufberater'
      fullPath: '/tools/kaufberater'
      preLoaderRoute: typeof ToolsKaufberaterRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/kalorien-rechner': {
      id: '/tools/kalorien-rechner'
      path: '/kalorien-rechner'
      fullPath: '/tools/kalorien-rechner'
      preLoaderRoute: typeof ToolsKalorienRechnerRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/kalorien': {
      id: '/tools/kalorien'
      path: '/kalorien'
      fullPath: '/tools/kalorien'
      preLoaderRoute: typeof ToolsKalorienRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/jobrad-leasing-rechner': {
      id: '/tools/jobrad-leasing-rechner'
      path: '/jobrad-leasing-rechner'
      fullPath: '/tools/jobrad-leasing-rechner'
      preLoaderRoute: typeof ToolsJobradLeasingRechnerRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/jobrad-leasing': {
      id: '/tools/jobrad-leasing'
      path: '/jobrad-leasing'
      fullPath: '/tools/jobrad-leasing'
      preLoaderRoute: typeof ToolsJobradLeasingRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/foerderung': {
      id: '/tools/foerderung'
      path: '/foerderung'
      fullPath: '/tools/foerderung'
      preLoaderRoute: typeof ToolsFoerderungRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/fahrrad-wetter': {
      id: '/tools/fahrrad-wetter'
      path: '/fahrrad-wetter'
      fullPath: '/tools/fahrrad-wetter'
      preLoaderRoute: typeof ToolsFahrradWetterRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/fahrrad-vergleich': {
      id: '/tools/fahrrad-vergleich'
      path: '/fahrrad-vergleich'
      fullPath: '/tools/fahrrad-vergleich'
      preLoaderRoute: typeof ToolsFahrradVergleichRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/eco-route': {
      id: '/tools/eco-route'
      path: '/eco-route'
      fullPath: '/tools/eco-route'
      preLoaderRoute: typeof ToolsEcoRouteRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/ebike-reichweite-rechner': {
      id: '/tools/ebike-reichweite-rechner'
      path: '/ebike-reichweite-rechner'
      fullPath: '/tools/ebike-reichweite-rechner'
      preLoaderRoute: typeof ToolsEbikeReichweiteRechnerRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/ebike-reichweite': {
      id: '/tools/ebike-reichweite'
      path: '/ebike-reichweite'
      fullPath: '/tools/ebike-reichweite'
      preLoaderRoute: typeof ToolsEbikeReichweiteRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/ebike-foerderung-rechner': {
      id: '/tools/ebike-foerderung-rechner'
      path: '/ebike-foerderung-rechner'
      fullPath: '/tools/ebike-foerderung-rechner'
      preLoaderRoute: typeof ToolsEbikeFoerderungRechnerRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/diebstahlschutz': {
      id: '/tools/diebstahlschutz'
      path: '/diebstahlschutz'
      fullPath: '/tools/diebstahlschutz'
      preLoaderRoute: typeof ToolsDiebstahlschutzRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/bussgeld': {
      id: '/tools/bussgeld'
      path: '/bussgeld'
      fullPath: '/tools/bussgeld'
      preLoaderRoute: typeof ToolsBussgeldRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/newsletter/bestaetigen': {
      id: '/newsletter/bestaetigen'
      path: '/newsletter/bestaetigen'
      fullPath: '/newsletter/bestaetigen'
      preLoaderRoute: typeof NewsletterBestaetigenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/abmelden': {
      id: '/newsletter/abmelden'
      path: '/newsletter/abmelden'
      fullPath: '/newsletter/abmelden'
      preLoaderRoute: typeof NewsletterAbmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fahrraeder/$slug': {
      id: '/fahrraeder/$slug'
      path: '/$slug'
      fullPath: '/fahrraeder/$slug'
      preLoaderRoute: typeof FahrraederSlugRouteImport
      parentRoute: typeof FahrraederRoute
    }
    '/artikel/$slug': {
      id: '/artikel/$slug'
      path: '/artikel/$slug'
      fullPath: '/artikel/$slug'
      preLoaderRoute: typeof ArtikelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mnv': {
      id: '/_authenticated/mnv'
      path: '/mnv'
      fullPath: '/mnv'
      preLoaderRoute: typeof AuthenticatedMnvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mnv/': {
      id: '/_authenticated/mnv/'
      path: '/'
      fullPath: '/mnv/'
      preLoaderRoute: typeof AuthenticatedMnvIndexRouteImport
      parentRoute: typeof AuthenticatedMnvRoute
    }
    '/_authenticated/mnv/users': {
      id: '/_authenticated/mnv/users'
      path: '/users'
      fullPath: '/mnv/users'
      preLoaderRoute: typeof AuthenticatedMnvUsersRouteImport
      parentRoute: typeof AuthenticatedMnvRoute
    }
    '/_authenticated/mnv/newsletter': {
      id: '/_authenticated/mnv/newsletter'
      path: '/newsletter'
      fullPath: '/mnv/newsletter'
      preLoaderRoute: typeof AuthenticatedMnvNewsletterRouteImport
      parentRoute: typeof AuthenticatedMnvRoute
    }
    '/_authenticated/mnv/messages': {
      id: '/_authenticated/mnv/messages'
      path: '/messages'
      fullPath: '/mnv/messages'
      preLoaderRoute: typeof AuthenticatedMnvMessagesRouteImport
      parentRoute: typeof AuthenticatedMnvRoute
    }
    '/_authenticated/mnv/media': {
      id: '/_authenticated/mnv/media'
      path: '/media'
      fullPath: '/mnv/media'
      preLoaderRoute: typeof AuthenticatedMnvMediaRouteImport
      parentRoute: typeof AuthenticatedMnvRoute
    }
    '/_authenticated/mnv/bikes': {
      id: '/_authenticated/mnv/bikes'
      path: '/bikes'
      fullPath: '/mnv/bikes'
      preLoaderRoute: typeof AuthenticatedMnvBikesRouteImport
      parentRoute: typeof AuthenticatedMnvRoute
    }
    '/_authenticated/mnv/auto-articles': {
      id: '/_authenticated/mnv/auto-articles'
      path: '/auto-articles'
      fullPath: '/mnv/auto-articles'
      preLoaderRoute: typeof AuthenticatedMnvAutoArticlesRouteImport
      parentRoute: typeof AuthenticatedMnvRoute
    }
    '/_authenticated/mnv/articles': {
      id: '/_authenticated/mnv/articles'
      path: '/articles'
      fullPath: '/mnv/articles'
      preLoaderRoute: typeof AuthenticatedMnvArticlesRouteImport
      parentRoute: typeof AuthenticatedMnvRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter/unsubscribe': {
      id: '/api/public/newsletter/unsubscribe'
      path: '/api/public/newsletter/unsubscribe'
      fullPath: '/api/public/newsletter/unsubscribe'
      preLoaderRoute: typeof ApiPublicNewsletterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter/dispatch': {
      id: '/api/public/newsletter/dispatch'
      path: '/api/public/newsletter/dispatch'
      fullPath: '/api/public/newsletter/dispatch'
      preLoaderRoute: typeof ApiPublicNewsletterDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/articles/auto-generate': {
      id: '/api/public/articles/auto-generate'
      path: '/api/public/articles/auto-generate'
      fullPath: '/api/public/articles/auto-generate'
      preLoaderRoute: typeof ApiPublicArticlesAutoGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/article-image/$path': {
      id: '/api/public/article-image/$path'
      path: '/api/public/article-image/$path'
      fullPath: '/api/public/article-image/$path'
      preLoaderRoute: typeof ApiPublicArticleImagePathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mnv/bikes_/new': {
      id: '/_authenticated/mnv/bikes_/new'
      path: '/bikes/new'
      fullPath: '/mnv/bikes/new'
      preLoaderRoute: typeof AuthenticatedMnvBikesNewRouteImport
      parentRoute: typeof AuthenticatedMnvRoute
    }
    '/_authenticated/mnv/bikes_/$id': {
      id: '/_authenticated/mnv/bikes_/$id'
      path: '/bikes/$id'
      fullPath: '/mnv/bikes/$id'
      preLoaderRoute: typeof AuthenticatedMnvBikesIdRouteImport
      parentRoute: typeof AuthenticatedMnvRoute
    }
    '/_authenticated/mnv/articles_/new': {
      id: '/_authenticated/mnv/articles_/new'
      path: '/articles/new'
      fullPath: '/mnv/articles/new'
      preLoaderRoute: typeof AuthenticatedMnvArticlesNewRouteImport
      parentRoute: typeof AuthenticatedMnvRoute
    }
    '/_authenticated/mnv/articles_/$id': {
      id: '/_authenticated/mnv/articles_/$id'
      path: '/articles/$id'
      fullPath: '/mnv/articles/$id'
      preLoaderRoute: typeof AuthenticatedMnvArticlesIdRouteImport
      parentRoute: typeof AuthenticatedMnvRoute
    }
  }
}

interface AuthenticatedMnvRouteChildren {
  AuthenticatedMnvArticlesRoute: typeof AuthenticatedMnvArticlesRoute
  AuthenticatedMnvAutoArticlesRoute: typeof AuthenticatedMnvAutoArticlesRoute
  AuthenticatedMnvBikesRoute: typeof AuthenticatedMnvBikesRoute
  AuthenticatedMnvMediaRoute: typeof AuthenticatedMnvMediaRoute
  AuthenticatedMnvMessagesRoute: typeof AuthenticatedMnvMessagesRoute
  AuthenticatedMnvNewsletterRoute: typeof AuthenticatedMnvNewsletterRoute
  AuthenticatedMnvUsersRoute: typeof AuthenticatedMnvUsersRoute
  AuthenticatedMnvIndexRoute: typeof AuthenticatedMnvIndexRoute
  AuthenticatedMnvArticlesIdRoute: typeof AuthenticatedMnvArticlesIdRoute
  AuthenticatedMnvArticlesNewRoute: typeof AuthenticatedMnvArticlesNewRoute
  AuthenticatedMnvBikesIdRoute: typeof AuthenticatedMnvBikesIdRoute
  AuthenticatedMnvBikesNewRoute: typeof AuthenticatedMnvBikesNewRoute
}

const AuthenticatedMnvRouteChildren: AuthenticatedMnvRouteChildren = {
  AuthenticatedMnvArticlesRoute: AuthenticatedMnvArticlesRoute,
  AuthenticatedMnvAutoArticlesRoute: AuthenticatedMnvAutoArticlesRoute,
  AuthenticatedMnvBikesRoute: AuthenticatedMnvBikesRoute,
  AuthenticatedMnvMediaRoute: AuthenticatedMnvMediaRoute,
  AuthenticatedMnvMessagesRoute: AuthenticatedMnvMessagesRoute,
  AuthenticatedMnvNewsletterRoute: AuthenticatedMnvNewsletterRoute,
  AuthenticatedMnvUsersRoute: AuthenticatedMnvUsersRoute,
  AuthenticatedMnvIndexRoute: AuthenticatedMnvIndexRoute,
  AuthenticatedMnvArticlesIdRoute: AuthenticatedMnvArticlesIdRoute,
  AuthenticatedMnvArticlesNewRoute: AuthenticatedMnvArticlesNewRoute,
  AuthenticatedMnvBikesIdRoute: AuthenticatedMnvBikesIdRoute,
  AuthenticatedMnvBikesNewRoute: AuthenticatedMnvBikesNewRoute,
}

const AuthenticatedMnvRouteWithChildren =
  AuthenticatedMnvRoute._addFileChildren(AuthenticatedMnvRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMnvRoute: typeof AuthenticatedMnvRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMnvRoute: AuthenticatedMnvRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface FahrraederRouteChildren {
  FahrraederSlugRoute: typeof FahrraederSlugRoute
}

const FahrraederRouteChildren: FahrraederRouteChildren = {
  FahrraederSlugRoute: FahrraederSlugRoute,
}

const FahrraederRouteWithChildren = FahrraederRoute._addFileChildren(
  FahrraederRouteChildren,
)

interface ToolsRouteChildren {
  ToolsBussgeldRoute: typeof ToolsBussgeldRoute
  ToolsDiebstahlschutzRoute: typeof ToolsDiebstahlschutzRoute
  ToolsEbikeFoerderungRechnerRoute: typeof ToolsEbikeFoerderungRechnerRoute
  ToolsEbikeReichweiteRoute: typeof ToolsEbikeReichweiteRoute
  ToolsEbikeReichweiteRechnerRoute: typeof ToolsEbikeReichweiteRechnerRoute
  ToolsEcoRouteRoute: typeof ToolsEcoRouteRoute
  ToolsFahrradVergleichRoute: typeof ToolsFahrradVergleichRoute
  ToolsFahrradWetterRoute: typeof ToolsFahrradWetterRoute
  ToolsFoerderungRoute: typeof ToolsFoerderungRoute
  ToolsJobradLeasingRoute: typeof ToolsJobradLeasingRoute
  ToolsJobradLeasingRechnerRoute: typeof ToolsJobradLeasingRechnerRoute
  ToolsKalorienRoute: typeof ToolsKalorienRoute
  ToolsKalorienRechnerRoute: typeof ToolsKalorienRechnerRoute
  ToolsKaufberaterRoute: typeof ToolsKaufberaterRoute
  ToolsKaufberaterAiRoute: typeof ToolsKaufberaterAiRoute
  ToolsLuftqualitaetRoute: typeof ToolsLuftqualitaetRoute
  ToolsPannenhilfeRoute: typeof ToolsPannenhilfeRoute
  ToolsRadelScoreRoute: typeof ToolsRadelScoreRoute
  ToolsRadelScoreGuideRoute: typeof ToolsRadelScoreGuideRoute
  ToolsRahmengroesseRoute: typeof ToolsRahmengroesseRoute
  ToolsRahmengroessenRechnerRoute: typeof ToolsRahmengroessenRechnerRoute
  ToolsReifendruckRoute: typeof ToolsReifendruckRoute
  ToolsReifendruckRechnerRoute: typeof ToolsReifendruckRechnerRoute
  ToolsSicherheitsCheckRoute: typeof ToolsSicherheitsCheckRoute
  ToolsSonnenzeitenRoute: typeof ToolsSonnenzeitenRoute
  ToolsStvoRoute: typeof ToolsStvoRoute
  ToolsTourenplanerRoute: typeof ToolsTourenplanerRoute
  ToolsUebersetzungRoute: typeof ToolsUebersetzungRoute
  ToolsUebersetzungRechnerRoute: typeof ToolsUebersetzungRechnerRoute
  ToolsVergleichRoute: typeof ToolsVergleichRoute
  ToolsVersicherungRoute: typeof ToolsVersicherungRoute
  ToolsWartungsintervalleRoute: typeof ToolsWartungsintervalleRoute
  ToolsWerkzeugListeRoute: typeof ToolsWerkzeugListeRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsBussgeldRoute: ToolsBussgeldRoute,
  ToolsDiebstahlschutzRoute: ToolsDiebstahlschutzRoute,
  ToolsEbikeFoerderungRechnerRoute: ToolsEbikeFoerderungRechnerRoute,
  ToolsEbikeReichweiteRoute: ToolsEbikeReichweiteRoute,
  ToolsEbikeReichweiteRechnerRoute: ToolsEbikeReichweiteRechnerRoute,
  ToolsEcoRouteRoute: ToolsEcoRouteRoute,
  ToolsFahrradVergleichRoute: ToolsFahrradVergleichRoute,
  ToolsFahrradWetterRoute: ToolsFahrradWetterRoute,
  ToolsFoerderungRoute: ToolsFoerderungRoute,
  ToolsJobradLeasingRoute: ToolsJobradLeasingRoute,
  ToolsJobradLeasingRechnerRoute: ToolsJobradLeasingRechnerRoute,
  ToolsKalorienRoute: ToolsKalorienRoute,
  ToolsKalorienRechnerRoute: ToolsKalorienRechnerRoute,
  ToolsKaufberaterRoute: ToolsKaufberaterRoute,
  ToolsKaufberaterAiRoute: ToolsKaufberaterAiRoute,
  ToolsLuftqualitaetRoute: ToolsLuftqualitaetRoute,
  ToolsPannenhilfeRoute: ToolsPannenhilfeRoute,
  ToolsRadelScoreRoute: ToolsRadelScoreRoute,
  ToolsRadelScoreGuideRoute: ToolsRadelScoreGuideRoute,
  ToolsRahmengroesseRoute: ToolsRahmengroesseRoute,
  ToolsRahmengroessenRechnerRoute: ToolsRahmengroessenRechnerRoute,
  ToolsReifendruckRoute: ToolsReifendruckRoute,
  ToolsReifendruckRechnerRoute: ToolsReifendruckRechnerRoute,
  ToolsSicherheitsCheckRoute: ToolsSicherheitsCheckRoute,
  ToolsSonnenzeitenRoute: ToolsSonnenzeitenRoute,
  ToolsStvoRoute: ToolsStvoRoute,
  ToolsTourenplanerRoute: ToolsTourenplanerRoute,
  ToolsUebersetzungRoute: ToolsUebersetzungRoute,
  ToolsUebersetzungRechnerRoute: ToolsUebersetzungRechnerRoute,
  ToolsVergleichRoute: ToolsVergleichRoute,
  ToolsVersicherungRoute: ToolsVersicherungRoute,
  ToolsWartungsintervalleRoute: ToolsWartungsintervalleRoute,
  ToolsWerkzeugListeRoute: ToolsWerkzeugListeRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgbRoute: AgbRoute,
  BarrierefreiheitRoute: BarrierefreiheitRoute,
  BildnachweiseRoute: BildnachweiseRoute,
  CookiesRoute: CookiesRoute,
  DatenschutzRoute: DatenschutzRoute,
  EBikesRoute: EBikesRoute,
  FahrraederRoute: FahrraederRouteWithChildren,
  FavoritenRoute: FavoritenRoute,
  ImpressumRoute: ImpressumRoute,
  KarteRoute: KarteRoute,
  KontaktRoute: KontaktRoute,
  MediadatenRoute: MediadatenRoute,
  MeinRadRoute: MeinRadRoute,
  MerklisteRoute: MerklisteRoute,
  NachrichtenRoute: NachrichtenRoute,
  NewsSitemapDotxmlRoute: NewsSitemapDotxmlRoute,
  NutzungsbedingungenRoute: NutzungsbedingungenRoute,
  PasstZuDirRoute: PasstZuDirRoute,
  RatgeberRoute: RatgeberRoute,
  RedaktionRoute: RedaktionRoute,
  SicherheitRoute: SicherheitRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestsRoute: TestsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  UeberUnsRoute: UeberUnsRoute,
  VergleichRoute: VergleichRoute,
  ArtikelSlugRoute: ArtikelSlugRoute,
  NewsletterAbmeldenRoute: NewsletterAbmeldenRoute,
  NewsletterBestaetigenRoute: NewsletterBestaetigenRoute,
  ApiPublicArticleImagePathRoute: ApiPublicArticleImagePathRoute,
  ApiPublicArticlesAutoGenerateRoute: ApiPublicArticlesAutoGenerateRoute,
  ApiPublicNewsletterDispatchRoute: ApiPublicNewsletterDispatchRoute,
  ApiPublicNewsletterUnsubscribeRoute: ApiPublicNewsletterUnsubscribeRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
